name: unittest

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'resources/**'
      - 'database/**'
      - 'config/**'

jobs:
  unittest:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel_admin_test
          MYSQL_USER: mysql
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        php: [ "8.2", "8.1" ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Composer install
        run: composer install

      - name: Composer run test
        run: composer run test
        env:
          MYSQL_HOST: 127.0.0.1
